config(tsconfig.json): Exclude `dist` dir
This fixes problems like:
```
error TS5055: Cannot write file <file-path> because it would overwrite input file.
```