config(@dendreth/balance-verification): Add project references
The `@dendreth/balance-verification` workspace rely on files from `@dendreth/relay`.
That is why we need to add this reference.

With this change following problem was resolved:
Running `yarn build-plonky-2` ends in:
```
error TS2688: Cannot find type definition file for 'node'.
  The file is in the program because:
    Entry point of type library 'node' specified in compilerOptions

relay/implementations/beacon-api.ts:543:9 - error TS2742: The inferred type of 'getBeaconBlock' cannot be named without a reference to '../../.yarn/unplugged/@lodestar-types-npm-1.17.0-1607a25762/node_modules/@lodestar/types/lib/utils/executionAddress'. This is likely not portable. A type annotation is necessary.

543   async getBeaconBlock(slot: bigint) {
            ~~~~~~~~~~~~~~

relay/implementations/beacon-api.ts:574:9 - error TS2742: The inferred type of 'getBeaconState' cannot be named without a reference to '../../.yarn/unplugged/@lodestar-types-npm-1.17.0-1607a25762/node_modules/@lodestar/types/lib/utils/executionAddress'. This is likely not portable. A type annotation is necessary.

574   async getBeaconState(slot: bigint) {
            ~~~~~~~~~~~~~~

Found 3 errors in the same file, starting at: relay/implementations/beacon-api.ts:543
```