config(@dendreth/solidity): Update `hardhat.config.ts` to use `tsconfig-paths`
Hardhat does not natively support TypeScript path aliases out of the box.
However, we can use `tsconfig-paths` package to achieve this.

With this we fix errors like this:
```
An unexpected error occurred:

Error: Your application tried to access @, but it isn't declared in your dependencies;
this makes the require call ambiguous and unsound.

Required package: @ (via "@/constants/network_config.json")
Required by: <path>/DendrETH/relay/utils/
```